import { ValueWishList } from "@import/providers/LandingPageProviders.jsx";

export type IMovieCardProps = {
  adult: boolean;
  backdrop_path: string;
  genre_ids: number[];
  origin_country?: string[];
  id: number;
  original_language: string;
  original_name?: string;
  original_title?: string;
  name?: string;
  overview: string;
  popularity: number;
  poster_path: string;
  release_date: string;
  title: string;
  video: boolean;
  vote_average: number;
  vote_count: number;
  first_air_date?: string;
  media_type?: string;
  isMovie?: boolean;
  forHover?: boolean;
  status?: boolean;
  children?: React.ReactNode;
  onMouseLeave?: any;
  onWishList: (value: ValueWishList) => void;
  type?: string;
  height?: number;
};
