import "./global.css";
import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import { Mulish } from "next/font/google";

import { WebVitals } from "@import/components/web-vitals";
import StyledComponentsRegistry from "@import/lib/registry";
import { LandingPageProvider } from "@import/providers/LandingPageProviders";

import Sidebar from "../components/Sidebar";
import Providers from "../providers/tanstackQueryProviders";

if (process.env.NEXT_PUBLIC_API_MOCKING === "enabled") {
  require("@import/lib/mocks/msw-init");
}

const MulishFont = Mulish({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={MulishFont.className}>
        <Providers>
          <StyledComponentsRegistry>
            <LandingPageProvider>
              <main>
                <WebVitals></WebVitals>
                <Sidebar></Sidebar>
                {children}
                <div id="portal-root"></div>
                <Analytics />
              </main>
            </LandingPageProvider>
          </StyledComponentsRegistry>
        </Providers>
      </body>
    </html>
  );
}
